name: DS Test site
favicon: null
layout_spectrum: 0.91913
typography_spectrum: 0.17619
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#242836'
    - '#b1b2b6'
    - '#e9effc'
    - '#92434d'
    - '#008575'
  brandStrength: 0.875
  lightness: 0.375
  saturation: 0.6875
  rhythmicContrast: 1
purpose: []
