name: DS Test site
favicon: null
layout_spectrum: 0.50551
typography_spectrum: 0.17619
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#242836'
    - '#b1b2b6'
    - '#e9effc'
    - '#92434d'
    - '#008575'
  brandStrength: 0.75
  lightness: 0.09357176604680717
  saturation: 0.5607187235727906
  rhythmicContrast: 0.25710032996721566
purpose: []
